services:
  postgres-primary:
    image: postgres:16
    container_name: scaling-reads-postgres-primary
    environment:
      POSTGRES_DB: scaling_reads
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d scaling_reads"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-replica:
    image: postgres:16
    container_name: scaling-reads-postgres-replica
    environment:
      POSTGRES_DB: scaling_reads
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d scaling_reads" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: scaling-reads-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_primary_data:
  postgres_replica_data:
  redis_data:
